### ISSUE TITLE
How mine the Ethereum Classic (ETC)

### ISSUE THREAD

**Issue by MirasakaDrakon** [CyberSecByte/termux-miner#3]
how to specify in a variable with the name of the Ethereum classic cryptocurrency?
![Screenshot_20240622-142653_Termux](https://github.com/CyberSecByte/termux-miner/assets/159175540/636fa387-f7ee-47d1-ae48-5271084b5242)

**Comment by CyberSecByte** [comment]
Well it depends on your pool. If you're using [nanopool](https://nanopool.org/) then it will be **Ethereum Classic**
