### ISSUE TITLE
I'm having an error

### ISSUE THREAD

**Issue by AnyLucu** [CyberSecByte/termux-miner#5]
In termux it's says
Setting executable permissions                Starting now
run.sh: line 20: ./xmrig: Permission denie
![Screenshot_2024-06-28-18-23-58-87_84d3000e3f4017145260f7618db1d683](https://github.com/CyberSecByte/termux-miner/assets/174117925/c402924e-68cb-44b8-abb9-b0ad9b88f3af)
d

**Comment by 0n1cOn3** [comment]
Please run

```chmod +x xmrig``` and try again

**Comment by AnyLucu** [comment]
> 

> Please run
> 
> `chmod +x xmrig` and try again

Not working i tried 
![Screenshot_2024-06-28-21-53-25-11_84d3000e3f4017145260f7618db1d683](https://github.com/CyberSecByte/termux-miner/assets/174117925/3afc5adc-f311-4590-af67-fb001c1eca18)

**Comment by CyberSecByte** [comment]
[Follow correctly what @0n1cOn3 told](https://github.com/CyberSecByte/termux-miner/issues/5#issuecomment-2197081176)
